(function(global) {
    var ap = [
        {
            "album_id":1,
            "personnel_id":1
        },
        {
            "album_id":1,
            "personnel_id":2
        },
        {
            "album_id":1,
            "personnel_id":3
        },
        {
            "album_id":1,
            "personnel_id":4
        },
        {
            "album_id":2,
            "personnel_id":1
        },
        {
            "album_id":2,
            "personnel_id":2
        },
        {
            "album_id":2,
            "personnel_id":3
        },
        {
            "album_id":2,
            "personnel_id":4
        },
        {
            "album_id":2,
            "personnel_id":5
        },
        {
            "album_id":2,
            "personnel_id":6
        },
        {
            "album_id":3,
            "personnel_id":1
        },
        {
            "album_id":3,
            "personnel_id":4
        },
        {
            "album_id":3,
            "personnel_id":7
        },
        {
            "album_id":3,
            "personnel_id":8
        },
        {
            "album_id":3,
            "personnel_id":9
        },
        {
            "album_id":4,
            "personnel_id":1
        },
        {
            "album_id":4,
            "personnel_id":10
        },
        {
            "album_id":4,
            "personnel_id":11
        },
        {
            "album_id":4,
            "personnel_id":12
        },
        {
            "album_id":5,
            "personnel_id":1
        },
        {
            "album_id":5,
            "personnel_id":2
        },
        {
            "album_id":5,
            "personnel_id":5
        },
        {
            "album_id":5,
            "personnel_id":6
        },
        {
            "album_id":6,
            "personnel_id":1
        },
        {
            "album_id":6,
            "personnel_id":13
        },
        {
            "album_id":6,
            "personnel_id":14
        },
        {
            "album_id":6,
            "personnel_id":15
        },
        {
            "album_id":6,
            "personnel_id":16
        },
        {
            "album_id":7,
            "personnel_id":1
        },
        {
            "album_id":7,
            "personnel_id":4
        },
        {
            "album_id":7,
            "personnel_id":7
        },
        {
            "album_id":7,
            "personnel_id":8
        },
        {
            "album_id":8,
            "personnel_id":1
        },
        {
            "album_id":8,
            "personnel_id":10
        },
        {
            "album_id":8,
            "personnel_id":11
        },
        {
            "album_id":8,
            "personnel_id":12
        },
        {
            "album_id":8,
            "personnel_id":16
        },
        {
            "album_id":9,
            "personnel_id":1
        },
        {
            "album_id":9,
            "personnel_id":10
        },
        {
            "album_id":9,
            "personnel_id":11
        },
        {
            "album_id":9,
            "personnel_id":12
        },
        {
            "album_id":10,
            "personnel_id":1
        },
        {
            "album_id":10,
            "personnel_id":13
        },
        {
            "album_id":10,
            "personnel_id":14
        },
        {
            "album_id":10,
            "personnel_id":15
        },
        {
            "album_id":10,
            "personnel_id":16
        },
        {
            "album_id":11,
            "personnel_id":1
        },
        {
            "album_id":11,
            "personnel_id":4
        },
        {
            "album_id":11,
            "personnel_id":7
        },
        {
            "album_id":11,
            "personnel_id":8
        },
        {
            "album_id":12,
            "personnel_id":1
        },
        {
            "album_id":12,
            "personnel_id":2
        },
        {
            "album_id":12,
            "personnel_id":3
        },
        {
            "album_id":12,
            "personnel_id":4
        },
        {
            "album_id":12,
            "personnel_id":5
        },
        {
            "album_id":12,
            "personnel_id":6
        },
        {
            "album_id":13,
            "personnel_id":1
        },
        {
            "album_id":13,
            "personnel_id":10
        },
        {
            "album_id":13,
            "personnel_id":11
        },
        {
            "album_id":13,
            "personnel_id":12
        },
        {
            "album_id":14,
            "personnel_id":1
        },
        {
            "album_id":14,
            "personnel_id":2
        },
        {
            "album_id":14,
            "personnel_id":5
        },
        {
            "album_id":14,
            "personnel_id":6
        },
        {
            "album_id":15,
            "personnel_id":1
        },
        {
            "album_id":15,
            "personnel_id":2
        },
        {
            "album_id":15,
            "personnel_id":3
        },
        {
            "album_id":15,
            "personnel_id":4
        },
        {
            "album_id":16,
            "personnel_id":1
        },
        {
            "album_id":16,
            "personnel_id":13
        },
        {
            "album_id":16,
            "personnel_id":14
        },
        {
            "album_id":16,
            "personnel_id":15
        },
        {
            "album_id":16,
            "personnel_id":16
        },
        {
            "album_id":17,
            "personnel_id":1
        },
        {
            "album_id":17,
            "personnel_id":10
        },
        {
            "album_id":17,
            "personnel_id":11
        },
        {
            "album_id":17,
            "personnel_id":12
        },
        {
            "album_id":18,
            "personnel_id":1
        },
        {
            "album_id":18,
            "personnel_id":2
        },
        {
            "album_id":18,
            "personnel_id":3
        },
        {
            "album_id":18,
            "personnel_id":4
        },
        {
            "album_id":19,
            "personnel_id":1
        },
        {
            "album_id":19,
            "personnel_id":3
        },
        {
            "album_id":19,
            "personnel_id":4
        },
        {
            "album_id":19,
            "personnel_id":5
        },
        {
            "album_id":20,
            "personnel_id":1
        },
        {
            "album_id":20,
            "personnel_id":13
        },
        {
            "album_id":20,
            "personnel_id":14
        },
        {
            "album_id":20,
            "personnel_id":15
        },
        {
            "album_id":20,
            "personnel_id":16
        },
        {
            "album_id":21,
            "personnel_id":1
        },
        {
            "album_id":21,
            "personnel_id":4
        },
        {
            "album_id":21,
            "personnel_id":7
        },
        {
            "album_id":21,
            "personnel_id":8
        },
        {
            "album_id":21,
            "personnel_id":9
        },
        {
            "album_id":22,
            "personnel_id":1
        },
        {
            "album_id":22,
            "personnel_id":5
        },
        {
            "album_id":22,
            "personnel_id":6
        },
        {
            "album_id":23,
            "personnel_id":1
        },
        {
            "album_id":23,
            "personnel_id":2
        },
        {
            "album_id":23,
            "personnel_id":3
        },
        {
            "album_id":23,
            "personnel_id":4
        },
        {
            "album_id":24,
            "personnel_id":1
        },
        {
            "album_id":24,
            "personnel_id":10
        },
        {
            "album_id":24,
            "personnel_id":11
        },
        {
            "album_id":24,
            "personnel_id":12
        },
        {
            "album_id":24,
            "personnel_id":16
        },
        {
            "album_id":25,
            "personnel_id":1
        },
        {
            "album_id":25,
            "personnel_id":4
        },
        {
            "album_id":25,
            "personnel_id":7
        },
        {
            "album_id":25,
            "personnel_id":8
        },
        {
            "album_id":26,
            "personnel_id":1
        },
        {
            "album_id":26,
            "personnel_id":10
        },
        {
            "album_id":26,
            "personnel_id":11
        },
        {
            "album_id":26,
            "personnel_id":12
        },
        {
            "album_id":26,
            "personnel_id":16
        },
        {
            "album_id":27,
            "personnel_id":1
        },
        {
            "album_id":27,
            "personnel_id":4
        },
        {
            "album_id":27,
            "personnel_id":7
        },
        {
            "album_id":27,
            "personnel_id":8
        },
        {
            "album_id":27,
            "personnel_id":9
        },
        {
            "album_id":28,
            "personnel_id":1
        },
        {
            "album_id":28,
            "personnel_id":4
        },
        {
            "album_id":28,
            "personnel_id":7
        },
        {
            "album_id":28,
            "personnel_id":8
        },
        {
            "album_id":29,
            "personnel_id":1
        },
        {
            "album_id":29,
            "personnel_id":2
        },
        {
            "album_id":29,
            "personnel_id":5
        },
        {
            "album_id":29,
            "personnel_id":6
        },
        {
            "album_id":30,
            "personnel_id":1
        },
        {
            "album_id":30,
            "personnel_id":2
        },
        {
            "album_id":30,
            "personnel_id":5
        },
        {
            "album_id":31,
            "personnel_id":1
        },
        {
            "album_id":31,
            "personnel_id":10
        },
        {
            "album_id":31,
            "personnel_id":11
        },
        {
            "album_id":31,
            "personnel_id":12
        },
        {
            "album_id":32,
            "personnel_id":1
        },
        {
            "album_id":32,
            "personnel_id":2
        },
        {
            "album_id":32,
            "personnel_id":3
        },
        {
            "album_id":32,
            "personnel_id":4
        },
        {
            "album_id":33,
            "personnel_id":1
        },
        {
            "album_id":33,
            "personnel_id":3
        },
        {
            "album_id":33,
            "personnel_id":5
        },
        {
            "album_id":33,
            "personnel_id":6
        },
        {
            "album_id":34,
            "personnel_id":1
        },
        {
            "album_id":34,
            "personnel_id":2
        },
        {
            "album_id":34,
            "personnel_id":5
        },
        {
            "album_id":34,
            "personnel_id":6
        },
        {
            "album_id":35,
            "personnel_id":1
        },
        {
            "album_id":35,
            "personnel_id":5
        },
        {
            "album_id":35,
            "personnel_id":6
        },
        {
            "album_id":36,
            "personnel_id":1
        },
        {
            "album_id":36,
            "personnel_id":4
        },
        {
            "album_id":36,
            "personnel_id":7
        },
        {
            "album_id":36,
            "personnel_id":8
        },
        {
            "album_id":37,
            "personnel_id":1
        },
        {
            "album_id":37,
            "personnel_id":2
        },
        {
            "album_id":37,
            "personnel_id":3
        },
        {
            "album_id":37,
            "personnel_id":4
        },
        {
            "album_id":37,
            "personnel_id":5
        },
        {
            "album_id":37,
            "personnel_id":6
        },
        {
            "album_id":38,
            "personnel_id":1
        },
        {
            "album_id":38,
            "personnel_id":4
        },
        {
            "album_id":38,
            "personnel_id":7
        },
        {
            "album_id":38,
            "personnel_id":8
        },
        {
            "album_id":39,
            "personnel_id":1
        },
        {
            "album_id":39,
            "personnel_id":2
        },
        {
            "album_id":39,
            "personnel_id":3
        },
        {
            "album_id":39,
            "personnel_id":4
        },
        {
            "album_id":39,
            "personnel_id":5
        },
        {
            "album_id":39,
            "personnel_id":6
        }
    ];

    global.exports['albums_personnel'] = ap.slice();
}(window));