(function(global) {
    var personnel = [
        {
            "id":1,
            "given_name":"Robert",
            "surname":"Fripp"
        },
        {
            "id":2,
            "given_name":"Adrian",
            "surname":"Belew"
        },
        {
            "id":3,
            "given_name":"Tony",
            "surname":"Levin"
        },
        {
            "id":4,
            "given_name":"Bill",
            "surname":"Bruford"
        },
        {
            "id":5,
            "given_name":"Trey",
            "surname":"Gunn"
        },
        {
            "id":6,
            "given_name":"Pat",
            "surname":"Mastelotto"
        },
        {
            "id":7,
            "given_name":"John",
            "surname":"Wetton"
        },
        {
            "id":8,
            "given_name":"David",
            "surname":"Cross"
        },
        {
            "id":9,
            "given_name":"Jamie",
            "surname":"Muir"
        },
        {
            "id":10,
            "given_name":"Mel",
            "surname":"Collins"
        },
        {
            "id":11,
            "given_name":"Boz",
            "surname":"Burrell"
        },
        {
            "id":12,
            "given_name":"Ian",
            "surname":"Wallace"
        },
        {
            "id":13,
            "given_name":"Michael",
            "surname":"Giles"
        },
        {
            "id":14,
            "given_name":"Ian",
            "surname":"McDonald"
        },
        {
            "id":15,
            "given_name":"Greg",
            "surname":"Lake"
        },
        {
            "id":16,
            "given_name":"Peter",
            "surname":"Sinfield"
        }
    ];

    global.exports['personnel'] = personnel.slice();
}(window));
